name: Release Branch Build & Tag

on:
  pull_request: # change to merge
    branches:
      - 'release/*'

jobs:
  publish:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Install JS dependencies
        run: pnpm install

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Rust dependencies
        run: cargo fetch
        working-directory: src-tauri

      - name: Get app version from tauri.conf.json
        id: tauri_version
        run: |
          APP_VERSION=$(jq -r .version src-tauri/tauri.conf.json)
          echo "tauri=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Get app version from Cargo.toml
        id: cargo_version
        run: |
          APP_VERSION=$(grep '^version =' src-tauri/Cargo.toml | awk '{print $3}' | tr -d '"')
          echo "cargo=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Get app version from package.json
        id: package_version
        run: |
          APP_VERSION=$(jq -r .version package.json)
          echo "package=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Check version consistency
        run: |
          if [ "${{ steps.tauri_version.outputs.tauri }}" != "${{ steps.cargo_version.outputs.cargo }}" ] || [ "${{ steps.tauri_version.outputs.tauri }}" != "${{ steps.package_version.outputs.package }}" ]; then
            echo "Version mismatch detected:" \
                 "tauri=${{ steps.tauri_version.outputs.tauri }}" \
                 "cargo=${{ steps.cargo_version.outputs.cargo }}" \
                 "package=${{ steps.package_version.outputs.package }}"
            exit 1
          fi

      - name: Install system dependencies (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libwebkit2gtk-4.1-dev libayatana-appindicator3-dev librsvg2-dev patchelf

      - name: Build Tauri app
        run: pnpm tauri build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tauri-build-${{ matrix.os }}
          path: |
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.rpm

      - name: Create pre-release tag with artifacts
        if: matrix.os == 'ubuntu-latest'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.tauri_version.outputs.tauri }}_pre
          name: Pre-release v${{ steps.tauri_version.outputs.tauri }}
          prerelease: true
          files: |
            src-tauri/target/release/bundle/**/*.AppImage
            src-tauri/target/release/bundle/**/*.dmg
            src-tauri/target/release/bundle/**/*.deb
            src-tauri/target/release/bundle/**/*.exe
            src-tauri/target/release/bundle/**/*.rpm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
